weather:
  start_year: 1991
  end_year: 2023

zones:
  nord:
    cities:
      - name: torino
        lat: 45.0703
        lon: 7.6869
      - name: milano
        lat: 45.4642
        lon: 9.1900
      - name: verona
        lat: 45.4384
        lon: 10.9916
      - name: bologna
        lat: 44.4949
        lon: 11.3426
  sud:
    cities:
      - name: napoli
        lat: 40.8518
        lon: 14.2681
      - name: bari
        lat: 41.1171
        lon: 16.8719
      - name: potenza
        lat: 40.6420
        lon: 15.8086
      - name: campobasso
        lat: 41.5603
        lon: 14.6684